### ISSUE TITLE
error handling 

### ISSUE THREAD

**Issue by tehfrag** [BigBrainAFK/tinfoil_gdrive_generator#2]
Running:
node index.js -source [FOLDER_ID] -auth -upload y -uploadDrive y
returns with error:
UnhandledPromiseRejectionWarning
(node:3152) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[error.txt](https://github.com/BigBrainAFK/tinfoil_gdrive_generator/files/4208977/error.txt)

**Comment by BigBrainAFK** [comment]
Fixed in 247820a
