### ISSUE TITLE
Hitting API limits

### ISSUE THREAD

**Issue by shinji257** [BigBrainAFK/tinfoil_gdrive_generator#4]
For some reason I keep getting errors regarding hitting API limits.  I have provided a credentials.json file and it does "authenticate" fine via that.  At first I noted that it was barely hitting over the 100 requests per 100 seconds limit so I bumped it to 1000 requests in that timeframe but I'm still getting an error.  This error doesn't seem to be handled at all so the whole script seems to die.

[removed]

EDIT: The issue appears to be random as I just ran it again (same command -- same target folder -- same credentials) and it went through without issue. o.O

**Comment by BigBrainAFK** [comment]
can you check developer console and check the request rate and maybe post a screenshot (blur out private details ofc) and i recommend you making new credentials since the log contains ur auth token

**Comment by BigBrainAFK** [comment]
i also recommend using service accounts to avoid using 1 user for all things. i had the same problem since 1 user did rclone, index and spreadsheet. its the reason why i implemented SA loading so i could use 2 SAs for index and spreadsheet respectively

**Comment by shinji257** [comment]
Thanks.  I removed it since you have seen it but I'll go around and reset the credentials when I have a moment to do so.  I'll also see about switching this and the spreadsheet to use SAs.

As for usage it peaked at around 170 for me for a 100 second period with my limit set at 1000 right now.  Can't screenshot now because it isn't showing it right now for some reason.  What got me was that I could generate and get an error then immediately do it again and it would go through fine.

**Comment by shinji257** [comment]
I'm having trouble switching this over to use SAs.  When I try I'm getting an error and I can't figure out why.

https://gist.github.com/shinji257/3777f0d31059eff23e0ec209543f891c

**Comment by shinji257** [comment]
Rate limit was implemented so closing this.

**Comment by BigBrainAFK** [comment]
just for future reference: your error with the SA is caused by the SA not being added to the shared drive and thus not being able to access the files. SAs have an email u need to add to the shared drive for them to work. I still do recommend using an SA since thats technically what they are intended for.

**Comment by shinji257** [comment]
Doh!  I feel like an idiot.  Of course the SAs work that I use for autorclone because those are on the drive.  I'll go back and fix it now that you have put me in my place for that.
