### ISSUE TITLE
All the names inside "new games" section are either obfuscated (using gdrive) or uc (using https [-oldformat flag])

### ISSUE THREAD

**Issue by AttackOfTheMoons** [BigBrainAFK/tinfoil_gdrive_generator#5]
Not sure if it is possible to create titledbs for all them, but if it was, that would make this insanely cool.

**Comment by BigBrainAFK** [comment]
i could theoretically provide names in the url but if i recall correctly this increases loading time due to parsing

**Comment by AttackOfTheMoons** [comment]
> i could theoretically provide names in the url but if i recall correctly this increases loading time due to parsing

How do you navigate the games without their titles? If it is possible to add as an optional flag i think that would be ideal

**Comment by BigBrainAFK** [comment]
I have added the game titles since this does, in fact, not slow down the loading process. Fixed in 955a335
