### ISSUE TITLE
Feature Request: Command Option to Set "success" Message

### ISSUE THREAD

**Issue by EchoApeiron** [BigBrainAFK/tinfoil_gdrive_generator#6]
Just a nice feature, currently when generating an index it creates a success message like the following: 

"Line1
Line2
Line3
Line4"

Or hardcode at least a signature for yourself ;)

**Comment by BigBrainAFK** [comment]
That text is talen from the `conf.json` and can be located in the motd field

**Comment by EchoApeiron** [comment]
Thank you for the quick response. I see it now and it makes perfect sense.
