### ISSUE TITLE
it is not working.

### ISSUE THREAD

**Issue by dalsim12** [BigBrainAFK/tinfoil_gdrive_generator#7]
i tried to make index file, but i got back next error msg. i couln't have index.

(node:35248) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'list' of undefined
    at C:\rclone\nodgen\index.js:588:38
    at new Promise (<anonymous>)
    at retrieveAllDrives (C:\rclone\nodgen\index.js:587:9)
    at choice (C:\rclone\nodgen\index.js:222:23)
    at C:\rclone\nodgen\index.js:158:4
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:35248) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:35248) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by BobGallardo** [comment]
I noticed the same thing today. Maybe installing a previous version of node will help?

**Comment by BigBrainAFK** [comment]
This means that the driveAPI couldnt initialize properly and/or you dont have any shared drives accessible on the account. I should probably add a check for this.

**Comment by BobGallardo** [comment]
> This means that the driveAPI couldnt initialize properly and/or you dont have any shared drives accessible on the account. I should probably add a check for this.

That solved my problem. Catching the error then displaying human readable message would be helpful. thanks
